name: Lint and test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    name: Lint and Jest tests

    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - run: npm run lint (Run ESLint)
      - run: npm run test (Run Jest)